<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TAKeyData\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
<ProjectReference Include="..\Modules\Report\Modules.Report.FBase\Modules.Report.FBase.csproj">
      <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
      <Private>True</Private>
      <ReferenceOutputAssembly></ReferenceOutputAssembly>
    </ProjectReference>
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.Compat" Version="2025.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FastReport">
      <HintPath>..\..\libs\Reports\FastReportFree\FastReport.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="FastReport.OpenSource.Export.PdfSimple">
      <HintPath>..\..\libs\Reports\FastReportFree\FastReport.OpenSource.Export.PdfSimple.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="FastReport.OpenSource.Web">
      <HintPath>..\..\libs\Reports\FastReportFree\FastReport.OpenSource.Web.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Modules.Report.Base">
      <HintPath>..\DLLs\Modules.Report.Base.dll</HintPath>
    </Reference>
    <Reference Include="Shared.Core">
      <HintPath>..\DLLs\Shared.Core.dll</HintPath>
    </Reference>
    <Reference Include="Shared.Infrastructure">
      <HintPath>..\DLLs\Shared.Infrastructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
