<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\Shared.DTO\Shared.DTO.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Shared.Reference\Shared.Reference.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Shared.Utility\Shared.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Shared.Core">
      <HintPath>..\..\..\..\DLLs\Shared.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
