services:
  tac-sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    container_name: tac_webapi_sqlserver
    user: root
    restart: always
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - tac_webapi_tac_sql_data:/var/opt/mssql/data

volumes:
  tac_webapi_tac_sql_data:
